export const NAVIGATION = {
  HOME: {
    HOME: 'NAVIGATION.HOME.HOME',
  },
  DETALLE: {
    DETALLE: 'NAVIGATION.DETALLE.DETALLE',
  },
  PROFILE: {
    PROFILE: 'NAVIGATION.PROFILE.PROFILE',
  },
  DRAWER: {
    DRAWER: 'NAVIGATION.DRAWER.DRAWER',
    MENU: 'NAVIGATION.DRAWER.MENU',
  },
};
